### ISSUE TITLE
Check for Capital Bound validates against wrong number

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#169]
**Bug Description**
Validation seems to be wrong because on the Stagenet I can't add baker with more than 22M CCDs. Given that Capital Bound is set to 40% and total stake is around 5 billion it should be possible to stake around 2 billion.
 
**Steps to Reproduce**
Use MW and try to stake 100M.

**Expected Result**
This should be possible.

**Actual Result**
This is not possible.

![image](https://user-images.githubusercontent.com/98821384/174023724-97e342d5-8708-475e-8f1a-431cf3d6aace.png)

**Versions**
- Software Version: 3.0.10 (94)
- OS: Android

**Comment by XOOPsoft** [comment]
Fixed in version 3.0.11 (95)

**Comment by mkmks** [comment]
I'm still getting a hint about the current maximum being around 22M on the "Update baker stake" screen.

**Comment by mkmks** [comment]
My bad, I used 3.0.10.
